apiVersion: v1
kind: Service

metadata:
  name: auto-rollback-service

spec:
  type: NodePort

  selector:
    app: auto-rollback-app

  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007